openapi: 3.1.0
info:
  title: Angola Weather API
  version: 1.0.0
  description: |
    API robusta para consulta de dados meteorológicos das principais localidades de Angola.
    **Principais Funcionalidades:**
    - **Clima Actual:** Obtenha as condições meteorológicas em tempo real para uma localidade específica.
    - **Listagem de Localidades:** Explore as localidades disponíveis.

    **Características Técnicas:**
    - **Alto Desempenho:** Cache inteligente com Redis para garantir respostas de baixa latência.
    - **Dados Confiáveis:** Informações meteorológicas fornecidas por provedores de alta precisão.
    - **Flexibilidade:** Suporte a unidades de medida métricas (Celsius).
  contact:
    name: Clima Angola API - Suporte
    email: baptistaalfredo81@gmail.com

servers:
  - url: https://api.clima-angola.ao/api/v1
    description: Produção
  - url: http://localhost:3000/api/v1
    description: Desenvolvimento

tags:
  - name: Localidades
    description: Operações relacionadas às localidades de Angola
  - name: Clima
    description: Consulta das condições meteorológicas actuais para uma localidade

paths:
  /localidade:
    get:
      tags: [Localidades]
      summary: Listar localidades
      description: Lista localidades de Angola com filtros opcionais.
      operationId: listLocations
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/PageSizeParam'
        - name: provincia
          in: query
          description: Filtra localidades por província
          schema:
            type: string
      responses:
        '200':
          description: Lista de localidades
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedLocations'
        '400':
          description: Parâmetros inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /localidade/{id}:
    get:
      tags: [Localidades]
      summary: Buscar localidade por ID
      operationId: getLocationById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Localidade encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        '404':
          description: Localidade não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /clima/{localidade}:
    get:
      tags: [Clima]
      summary: Clima actual por nome da localidade
      operationId: getWeatherByLocationId
      parameters:
        - name: localidade
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Clima actual retornado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseWeather'
        '404':
          description: Localidade não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseErro'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseErro'
        '502':
          description: Timeout ou falha na API externa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseErro'

components:
  schemas:
    Location:
      type: object
      properties:
        id:
          type: integer
          example: 123
        name:
          type: string
          example: "Talatona"
        slug:
          type: string
          example: "talatona"
        provincia:
          type: string
          example: "Luanda"

    WeatherCurrent:
      type: object
      properties:
        temperatura:
          type: number
          format: float
          example: 23.4
        sensacaoTermica:
          type: number
          format: float
          example: 22.1
        humidadeRelativa:
          type: integer
          example: 68
        descricao:
          type: string
          example: "parcialmente nublado"

    ApiResponseWeather:
      type: object
      properties:
        sucesso:
          type: boolean
          example: true
        mensagem:
          type: string
          example: "Clima actual obtido com sucesso"
        dados:
          $ref: '#/components/schemas/WeatherCurrent'

    ApiResponseErro:
      type: object
      properties:
        sucesso:
          type: boolean
          example: false
        mensagem:
          type: string
          example: "Erro na chamada à API de clima"
        erros:
          type: array
          items:
            type: string
          example: ["timeout of 1000ms exceeded"]
